### DISCUSSION TITLE
How is the "Next Trains" block in the "Neighborhood" view made?

### DISCUSSION THREAD

**Discussion by johanohly** [Madelena/hass-config-public#18] [Q&A] [answered]
It's in the `!include secret/neighborhood-transit.yaml` file which is not shared because it obviously contains something secret...

**Comment by johanohly** [comment]
I do know how to get the actual transit data, just the display is my struggle :)

**Comment by modelstudent101** [comment, marked as answer]
Right -- I spent some time re-creating this.

The card uses the multiple-entity row from HACS.

Here's a formatted card. I don't have the "Next train" due yet, as I just figured this out fiddling around a few minutes ago. I remembered your post, and thought I would share the love. @Madelena, I think, added some padding to the sections, as I've seen it in some other cards.

```yaml
type: entities
entities:
  - entity: sensor.l_to_manhattan
    name: "L to Manhattan"
    icon: mdi:subway
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: Due in
        unit: min
        styles:
          text-align: left
      - attribute: Due at
        styles:
          text-align: left
  - entity: sensor.l_to_manhattan
    type: custom:multiple-entity-row
    show_state: false
    name: ' '
    icon: ' '
    entities:
      - attribute: Next due
        unit: min
      - attribute: Next train
        styles:
          text-align: left
  - type: section
  - entity: sensor.l_to_Canarsie
    name: "L to Canarsie"
    icon: mdi:subway
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: Due in
        unit: min
        styles:
          text-align: left
      - attribute: Due at
        styles:
          text-align: left
  - entity: sensor.l_to_canarsie
    type: custom:multiple-entity-row
    show_state: false
    name: ' '
    icon: ' '
    entities:
      - attribute: Next due
        unit: min
      - attribute: Next train
        styles:
          text-align: left
```

`name:` and `icon:` need to have a placeholder in order to display nothing. I did this by including a blank space (`' '`), which ended up clearing the names. I added a `-type: section` even though it's not visible in the card, simply because I suspect madelena uses it for adding padding.

This should get you started. You'll either have to set up a conditional card, so that null entries aren't displayed, or edit the GTFS sensor, so that the unit is included if it's not null.
