### ISSUE TITLE
OpenSky extended sensors

### ISSUE THREAD

**Issue by marvandorth** [Madelena/hass-config-public#1]
Ok! 
So I had time to play a little bit with your magnificent dashboard!
I'm really liking it so far but I was wondering how you created the sensors for opensky integration...
It's this part in your neighborhood.yaml file;
```
`- type: conditional
    conditions:
      - entity: sensor.opensky_flight_in_vicinity
        state_not: 'off'
    card:
      type: vertical-stack
      cards:
        - type: entities
          entities:
            - entity: sensor.opensky_flight_friendly_name
              type: 'custom:multiple-entity-
![Capture](https://user-images.githubusercontent.com/4710453/171213264-d716895d-ad3e-413f-a19c-7bf714545cac.PNG)
row'
              name: ' '
              show_state: false
              secondary_info:
                entity: sensor.opensky_flight_friendly_name
        - type: horizontal-stack
          cards:
            - type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.opensky_origin_airport_code
                  name: Origin
                - show_name: false
                  show_icon: false
                  show_state: true
                  type: glance
                  entities:
                    - entity: sensor.opensky_origin_city
                      card_mod:
                        style: |
                          div {text-align: left;}
                  style: |
                    .entity {padding: 0 !important; margin: -16px 0}
            - type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.opensky_destination_airport_code
                  name: Destination
                - show_name: false
                  show_icon: false
                  show_state: true
                  type: glance
                  entities:
                    - entity: sensor.opensky_destination_city
                      card_mod:
                        style: |
                          div {text-align: left;}
                  style: |
                    .entity {padding: 0 !important; margin: -16px 0}
        - type: entities
          entities:
            - entity: sensor.opensky_flight_in_vicinity
              type: 'custom:multiple-entity-row'
              name: ' '
              secondary_info:
                attribute: movement
              show_state: false
              entities:
                - attribute: altitude
                  name: Altitude
      in_card: true`
```

**Comment by Madelena** [comment]
I scraped most of the information from Radarbox using the flight number provided by OpenSky using ha-multiscrape, and it is triggered by an automation using the OpenSky Enter event. I'm hesistant to share scrapes since they will get blocked if their devs find out. Here's an excerpt:

```yaml
- resource_template: > 
    {{
      iif( (state_attr('sensor.opensky_flight_in_vicinity', 'altitude') | int(0) > 100)
        and ((states('sensor.opensky_flight_in_vicinity')[0] != "N") or (states('sensor.opensky_flight_in_vicinity')[1] | int(-1) < 0)),
        "https://www.radarbox.com/data/flights/" + states('sensor.opensky_flight_in_vicinity'), "https://google.com"
      )
    }}
  name: OpenSky Radarbox Tracker
  scan_interval: 604800
  sensor:
    - unique_id: opensky_flight_friendly_name
      name: Flight Friendly Name
      select: "title"
      value_template: '{{ (value.split(" - ")[1]) + " " + (value.split(" - ")[0]) }}'
      icon: mdi:airplane
```
