### ISSUE TITLE
Network Rail Map layout issue

### ISSUE THREAD

**Issue by RolandWijnen** [Madelena/hass-config-public#36]
I've setup the Network Rail Map reflecting my network topology as shown in the screenshot. 

<img width="340" alt="Screenshot 2024-11-16 at 20 38 06" src="https://github.com/user-attachments/assets/2c8f2006-70a1-4ad7-a6e3-e1923d86e779">

There is one detail that I can't figure out as highlighted in the screenshot. I searched for documentation for the Network Rail Map but could not find anything online. Hope someone here can point me in the right direction. 

This is the code of the rail_interchange_row, including the rail5_bottom_entity point to the Iron Man node below.

```              
              - entity: sensor.ping_edgerouter_er12
                type: 'custom:button-card'
                template: rail_interchange_row
                variables:
                  rail0_bottom_entity: sensor.ping_ps316g_switch
                  rail1_bottom_entity: sensor.ping_edgemax_16_150w_switch
                  rail2_bottom_entity: sensor.ping_ubiquiti_uap_outside
                  rail2_top_entity: sensor.ping_kpn_experia_box
                  rail3_bottom_entity: sensor.ping_blackwidow
                  rail4_bottom_entity: sensor.ping_doctorstrange
                  rail5_bottom_entity: sensor.ping_ironman
                  station_size_from: 0
                  station_size_to: 5
                name: EdgeRouter 12
                label: '192.168.0.1'
                state_display: '[[[ return entity.attributes.round_trip_time_avg ? (Math.round(entity.attributes.round_trip_time_avg)) + "ms" : "Off" ]]]'
```

This is the code of the Iron Man node with all the rail entities defined:

```          
              - entity: sensor.ping_ironman
                type: 'custom:button-card'
                template: rail_station_row
                variables:
                  rail0_entity: sensor.ping_ps316g_switch
                  rail1_entity: sensor.ping_edgemax_16_150w_switch
                  rail2_entity: sensor.ping_ubiquiti_uap_outside
                  rail3_entity: sensor.ping_blackwidow
                  rail4_entity: sensor.ping_doctorstrange
                  rail5_entity: sensor.ping_ironman
                  station_rail: 5
                  terminate_at: bottom
                name: Iron Man
                label: '192.168.50.2'
                state_display: '[[[ return entity.state ]]]'
```
                
However the line (rail5_entity: sensor.ping_ironman) does not appear. What am I missing?
